# Generated by Django 5.1.7 on 2025-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_alter_student_caddr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cAddr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
